[package]
name = "langton"
version = "0.1.0"
edition = "2024"
license = "GPL-3.0"

[dependencies]
env_logger = "0.11.8"
log = "0.4.29"
pixels = "0.13.0"
winit = { version = "0.29", features = ["rwh_05"]}